spring:
  config:
    import:
      - optional:classpath:/secrets.yaml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 9
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false