# name: Deploy Action

# on:
#   push:
#     branches: [main]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - uses: actions/setup-java@v3
#         with:
#           distribution: 'temurin'
#           java-version: '17'

#       - run: touch ./src/main/resources/secrets.yaml
#       - run: echo "${{ secrets.APPLICATION_SECRETS }}" > ./src/main/resources/secrets.yaml

#       - run: chmod +x gradlew
#       - run: ./gradlew clean build -x test
#       - run: mv build/libs/today_i_baekjoon-0.0.1.jar ./

#       - name: Deliver File
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.REMOTE_HOST }}
#           username: ${{ secrets.REMOTE_USER }}
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           port: ${{ secrets.REMOTE_SSH_PORT }}
#           source: "today_i_baekjoon-0.0.1.jar"
#           target: "today_i_baekjoon"
#           overwrite: true

#       - name: Deploy to Server
#         uses: appleboy/ssh-action@master
#         with:
#           key: ${{ secrets.SSH_PRIVATE_KEY }}
#           host: ${{ secrets.REMOTE_HOST }}
#           username: ${{ secrets.REMOTE_USER }}
#           port: ${{ secrets.REMOTE_SSH_PORT }}
#           script: |
#             sudo kill $(ps -ef | grep '[0-9] java -jar today_i_baekjoon-0.0.1.jar$' | awk '{print $2}') || true
#             cd today_i_baekjoon
#             chmod +x today_i_baekjoon-0.0.1.jar
#             sudo rm nohup.out
#             sudo nohup java -jar today_i_baekjoon-0.0.1.jar > nohup.out 2> nohup.err < /dev/null &