name: Deploy Action

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: chmod +x gradlew
      - run: ./gradlew clean build -x test

      - name: Deliver File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          source: "build/libs/*.jar"
          target: "today_i_baekjoon/libs"
          rm: true

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            sudo kill $(ps -ef | grep '[0-9] java -jar today_i_baekjoon-0.0.1.jar$' | awk '{print $2}')
            cd today_i_baekjoon
            sudo nohup java -jar ./libs/today_i_baekjoon-0.0.1.jar &